name: Deploy to HF Spaces (new version); indent with 2 spaces

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add Hugging Face Space as a remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf-space https://hf:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/McPega/imagegpt

      - name: Push to HF Space
        run: |
          git push --force hf-space main
